# Generated by Django 4.1.4 on 2022-12-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Subject'),
        ),
    ]
