# Generated by Django 3.2.4 on 2021-07-10 04:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True, verbose_name='ngày cập nhật')),
                ('csv_file', models.FileField(upload_to='students/bulkupload/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('Female', 'Female')], default='male', max_length=10, verbose_name='Gender')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, verbose_name='Birth day')),
                ('age', models.IntegerField(choices=[('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], default=15, verbose_name='age')),
                ('parent_mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')], verbose_name='Parent phone number')),
                ('email', models.CharField(default=None, max_length=30, validators=[django.core.validators.EmailValidator(message='Email is not valid')])),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('passport', models.ImageField(blank=True, upload_to='students/passports/', verbose_name='avartar')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.studentclass', verbose_name='Class')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
